### PR TITLE
base singleuser-sample on docker-stacks

### PR DESCRIPTION
**Pull request by minrk**
Use smallest base-notebook with placeholder for installation of packages.

The main change needed is to set WORKDIR to $HOME instead of the default $HOME/work in order for volume persistence to work

I'm *pretty sure* this works, but I haven't been able to do a full deployment to confirm. We can investigate further next week.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Let's test this out during the sprints!

Ideally, I don't want this image to be here at all, and we should just refer to the dockerstack image directly. We can set WORKDIR in kubespawner now, and we can probably find a solution for the CMD too.

**Comment by minrk** [comment]
> we can probably find a solution for the CMD too.

What I'd really love is to inject the `start-singleuser.sh` at launch time on any image, so that there can't possibly be a version mismatch between the Spawner and the launch script. But I don't know how to do that reliably.

**Comment by yuvipanda** [comment]
Yeah, I agree. What I *really* want is a static compiled small single binary we can inject into any image to make it work with JupyterHub. This will also be really nice for binder, where we now have to assume there'll be a jupyerhub-singleuser in PATH.

We can add a feature to kubespawner to do this injection - either with an init container, a pre-start hook or just an exec. If jupyterhub-singleuser was a self contained single file we can try that too now...

But that's a separate use case, I guess! Also I think we don't need CMD at all right now, since jupyterhub-singleuser *is* in PATH in docker stacks.

**Comment by minrk** [comment]
> What I really want is a static compiled small single binary we can inject into any image to make it work with JupyterHub

That would be awesome. If we just rewrote all of JupyterHub in Go...

> If jupyterhub-singleuser was a self contained single file we can try that too now...

It would still have dependencies, so it would need to assume some degree of notebook and/or python installed, and bundle everything that's missing. If we assume `notebook` is installed, this can be a self-extracting shell script including the jupyterhub wheel, such as something like:

```bash
cat <<EOF_B64 > /tmp/jupyterhub.whl
JUPYTERHUB_WHL_DATA
EOF_B64

pip install /tmp/jupyterhub.whl
exec jupyterhub-singleuser $@
```


> Also I think we don't need CMD

We don't need CMD if kubespawner overrides it by default (and/or in this helm config somewhere). Is that the case? DockerSpawner trusts the image to set the launch command by default, so this would be needed over there.

**Comment by yuvipanda** [comment]
@minrk said he'll open this back up in new repo!

**Pull request closed without merging**
