### PR TITLE
Upgrade pip because upgrade pip.

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by willingc** [comment]
Thanks @Carreau

**Comment by yuvipanda** [comment]
I explicitly don't want us to do this for now. I'll explain in a bit...

**Comment by yuvipanda** [comment]
Missed a bus, so 'a bit' is now :)

1. This makes the image being built non-deterministic. It'll get a different version of pip each time we build it. 
2. It adds another axes to the package management set of axes (ubuntu version, python version, pip version). Ideally I want ubuntu version to imply both python and pip version, so we can just say 'ubuntu 17.04' rather than 'ubuntu 17.04 and pip 9.0.1', since the latter implies variants we might have to also support ('ubuntu 17.04 and pip 8.x', 'ubuntu 17.04 and pip 10')
3. Ubuntu 17.04 actually has pip 9.0, so should solve our problems. Upgrading the FROM to 17.04 is welcome, and I might do that soon myself :)

**Comment by willingc** [comment]
Makes sense. Really would like to have pip 9.x if we can :-) Thanks for the explanation.

**Comment by yuvipanda** [comment]
@willingc https://github.com/jupyterhub/helm-chart/pull/17 gets pip 9.x :)

**Pull request merged**
