### PR TITLE
Update hublogo URL for all existing charts

### PR DESCRIPTION
**Pull request by manics**
```
sed -i 's|https://jupyter.org/assets/hublogo.svg|https://jupyterhub.github.io/helm-chart/images/hublogo.svg|' index.yaml
```

This should be the last step!

### CODE REVIEW

**Comment by consideRatio** [comment]
Hmmmm im not sure... I think this will cause warnings like: mismatch between index and package, which had a checksum.

This shouldnt be done!

**Comment by manics** [comment]
That's a pain :disappointed: 
Maybe we should get the logo (or a redirect?) put back on the main jupyter website then?

**Comment by consideRatio** [comment]
> Maybe we should get the logo (or a redirect?) put back on the main jupyter website then?

Hmmm, but I don't think there is any issue - or is there? I that they don't make sure all logos of old Chart.yaml files are valid - that would be a pain :)

I'm quite confident the policy they want is that you shouldn't modify already released charts etc, so, if they report "oh no broken link" of old Chart.yaml entries in the Helm repo's index.yaml file - then I think that they should update that behavior to not do that instead - at least not more than once.

I assumed we didn't have any issue any more - that as soon as we stopped adding more broken releases we would be fine, that it only checked new releases being added.

**Review by consideRatio — CHANGES_REQUESTED** [review]
Just marking this like this to clarify we shouldn't merge this.

**Comment by consideRatio** [comment]
Closing as we shouldn't update published chart's metadata in the helm chart repo's index.yaml, as its checked for consistency against the packaged helm chart's Chart.yaml file.

We could take action to try fix old broken logo links for past releases, but its not important enough to resolve I think.

**Pull request closed without merging**
